pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('Dockerhub')
	}
    stages {
        stage('Docker Login') {
            steps {
               withCredentials([usernamePassword(credentialsId: 'mycreds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
               sh 'cf login some.awesome.url -u $USERNAME -p $PASSWORD'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh """
                cd laravel-app
                ansible-playbook playbook.yml
                """
            }
        }
        stage('Run Dockercompose playbook') {
            steps {
                sh """
                cd laravel-app
                ansible-playbook playbook-dcompose.yml 
                """
            }
        }
    }
}
